server:
  port: 8080
#  servlet:
#    context-path: /api
spring:
  profiles:
    active: dev
  application:
    name: mybatis-plus


#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
# 是否要开启 mp sql输出日志
# configuration:
#   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  typeEnumsPackage: com.aaa.mybatisplus.domain.enums
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      # 这里的自定义的字段是 数据库映射的实体类映射 eg： is_del =>  isDel
      #但如果实体类上有 @TableLogic 则以实体上的为准，忽略全局。 即先查找注解再查找全局，都没有则此表没有逻辑删除。
      logic-delete-field: isDel  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

---
server:
  workerId: 0
  #雪花算法的数据中心id，在java 启动命令中定义，四台为0，1，2，3
  datacenterId: 0

#加密参数(加盐)
jasypt:
  encryptor:
    password: 123
