spring:
  datasource:
    dynamic:
      hikari:  # 全局hikariCP参数，所有值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        catalog:
        max-lifetime: 1500000
        connection-timeout: 30000
        idle-timeout: 30000
        pool-name: SpringBootHikariCP
        min-idle: 3
        max-pool-size: 8
      datasource:
        master:
          username: root
          password: 123456
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://127.0.0.1:3301/master?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
          hikari: # 以下参数针对每个库可以重新设置hikari参数
            max-pool-size:
            idle-timeout:
        #           ......
        slave:
          username: root
          password: 123456
          url: jdbc:p6spy:mysql://127.0.0.1:3301/slave?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          druid:
            initial-size: 6
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    database1: 1
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      shutdown-timeout: 100 # 关闭超时时间
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 10000 #连接超时的时间
    #    cluster:
    #      nodes: 47.98.253.2:7001,47.98.253.2:7002,47.98.253.2:7003,47.98.253.2:7004,47.98.253.2:7005,47.98.253.2:7006
  redisson:
    host: 127.0.0.1
    port: 6379
    password:
    #redisson 自定义 redisson 集群节点
    clusters: 47.98.253.2:7001,47.98.253.2:7002,47.98.253.2:7003,47.98.253.2:7004,47.98.253.2:7005,47.98.253.2:7006
    #sentinel/cluster/single
    mode: single

swagger:
  enabled: true
  title: mybatis-plus
  description: 以mybatis-plus为主题整理企业级常用组件
  base-package: com.aaa
  version: 1.0.0
  termsOfServiceUrl: http://tlzallen.top/
  contact:
    name: liuzhen.tian
    url:   http://lalala.com
    email: tlzAllen163.com
  authorization:
    key-name: Authorization
    name: auth-token
    auth-regex: ^.*$
  base-path: /**
  exclude-path: /error, /ops/**

knife4j:
  basic:
    enable: true
    password: 123456
    username: admin


#测试自定义属性 映射到yml
dept:
  dept-name: '部门旧名字'
test:
  oldName: '旧名字'

#测试 springboot-yml内list、map组合写法
# list 和 map 均有两种写法，不可同时存在，否则无法解析
my-props:
  varmaplist:
    key11:
      - t1
      - t2
    key22:
      - t11
      - t22
  list:   #list 写法 1 （行内写法）
   [topic1,topic2,topic3]
#  list: #list 写法 2
#    - topic1
#    - topic2
#    - topic3

#  cityList: #复杂类型 写法1
#    - cityName: 杭州
#      cityCode: 100001
#    - cityName: 上海
#      cityCode: 100002

  cityList[0]:  #复杂类型 写法2
    cityName: 杭州
    cityCode: 100001

  maps: # maps 写法 1 （行内写法）
    {key1: 'value1', key2: 'value2'}
#  maps: # maps 写法 2
#    key3: value3
#    key4: value4
